name: Sonarqube Analysis

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run SonarQube analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_HOST_URL: http://3.81.62.147:9000
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
